# system setup
num_time_steps: 50
training_set:
  batch_size: 512
  min_num_atoms: 3
  max_num_atoms: 6
test_set:
  batch_size: 20
  min_num_atoms: 2
  max_num_atoms: 7
unit_cell:
  xlo: -4
  ylo: -4
  xhi: 4
  yhi: 4

# simulator settings:
cutoff: 3
step_size: 0.1

# optimizer
learning_rate: 1.e-3

# model
mlp_hidden_size: 16
latent_size: 16
mlp_num_hidden_layers: 2
num_message_passing_steps: 1

# training
log_increment: 1000
num_training_iterations: 100000
# when loading or saving weights, the following paths are concatenated, thus place directory delimiters appropriately
model_save_directory:
  parent: models/
  child: demo_big/weights


