# system setup
num_time_steps: 50
training_set:
  batch_size: 256
  min_num_atoms: 3
  max_num_atoms: 6
test_set:
  batch_size: 10
  min_num_atoms: 3
  max_num_atoms: 6
unit_cell:
  xlo: -4
  ylo: -4
  xhi: 4
  yhi: 4

# simulator settings:
cutoff: 3
step_size: 0.1

# optimizer
learning_rate: 1.e-3

# model
mlp_hidden_size: 16
latent_size: 16
mlp_num_hidden_layers: 2
num_message_passing_steps: 1

# training
log_increment: 500
num_training_iterations: 10000
model_save_directory: models/

models/md_1_1:
  00e+04_50_0:
    1_3/weights-1:

